site_name: RadRocks EPK
site_url: https://radrocks.github.io/epk/
repo_url: https://github.com/radrocks/epk
repo_name: radrocks/epk

theme:
  favicon: assets/logo.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    scheme: slate
    primary: lime
    accent: green
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: True

plugins:
  - search
  - awesome-pages

extra:
  social:
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/RadRocksVIP
      - icon: fontawesome/solid/envelope
        link: mailto:radioactiverocks@gmail.com

extra_css:
  - css/extra.css